version: '3'

services:
  cms:
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.cms.rule=Host(`cms.${DOMAIN?:err}`)
      - traefik.http.routers.cms.service=cms
      - traefik.http.services.cms.loadbalancer.server.port=80
      - traefik.http.routers.ks.middlewares=authelia
      - homepage.name=Blog CMS
      - homepage.href=https://cms.${DOMAIN?:err}
      - homepage.description=CryingPotato CMS
      - homepage.group=Writing
      - homepage.icon=mdi-pencil

networks:
  traefik_default:
    external: true
